version: 2

defaults: &defaults
  working_directory: ~/wealthsimple
  docker:
    - image: circleci/node:10.12.0

references:
  attach_code_workspace: &attach_code_workspace
    attach_workspace:
      at: ~/wealthsimple

jobs:
  checkout_and_test:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - persist_to_workspace:
          root: .
          paths: .

  release:
    <<: *defaults
    steps:
      - checkout
      - *attach_code_workspace
      - run: |
          export NPM_TOKEN="${PUBLIC_NPM_TOKEN}"
          GH_TOKEN="${DEVTOOLS_GITHUB_API_TOKEN}" yarn run semantic-release
workflows:
  version: 2
  build:
    jobs:
      - checkout_and_test:
          context: wealthsimple
      - release:
          context: wealthsimple
          filters:
            branches:
              only: master
          requires:
            - checkout_and_test
