version: 2.1

orbs:
  micro-app: wealthsimple/micro-app@dev:master

references:
  parameters: &parameters
    packages: >-
      packages/eslint-config
executors:
  node:
    working_directory: /home/circleci/wealthsimple
    docker:
      - image: wealthsimple/node:12-ci

jobs:
  checkout-yarn:
    executor: node
    working_directory: /home/circleci/wealthsimple
    steps:
      - checkout
      - restore_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
      - micro-app/allow_github_host_key_verification
      - run:
          name: Install npm dependencies
          command: |
            npm config set _auth "$NEXUS_NPM_DEV_TOKEN"
            yarn install --no-progress --frozen-lockfile
      - save_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths: .

  semantic-release:
    executor: node
    steps:
      - micro-app/attach_code_workspace
      - micro-app/allow_github_host_key_verification
      - run: |
          GITHUB_TOKEN="$DEVTOOLS_GITHUB_API_TOKEN" \
          NPM_TOKEN="$NEXUS_CIRCLE_CI_TOKEN" \
          yarn workspaces run semantic-release -e semantic-release-monorepo-config --npm-publish
workflows:
  version: 2
  commit-workflow:
    jobs:
      - checkout-yarn:
          context: wealthsimple
      - micro-app/security:
          context: wealthsimple
          requires:
            - checkout-yarn
      - semantic-release:
          context: wealthsimple
          requires:
            - checkout-yarn
          filters:
            branches:
              only: master
